<a href="https://colab.research.google.com/github/vaibhavmahendru/EYGDS/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
ages = [25,23,35,45,14,22]
ages
print(type(ages))

<class 'list'>


In [12]:
age = np.array(ages)
print(type(age))
print(age)

<class 'numpy.ndarray'>
[25 23 35 45 14 22]


In [13]:
print(age.size)
print(age.shape)

6
(6,)


In [14]:
ZeroArray = np.zeros(3)
ZeroArray

array([0., 0., 0.])

In [29]:
weight = [50,60,70,80,55,85]

In [30]:
people = np.array([ages , weight])
print(type(people))

<class 'numpy.ndarray'>


In [31]:
print(people)
print(people.size)
print(people.shape)

[[25 23 35 45 14 22]
 [50 60 70 80 55 85]]
12
(2, 6)


In [36]:
people = people.reshape(1,12)
print("people : \t ",people)
print("shape : \t ",people.shape)
print("size : \t ",people.size)

people : 	  [[25 23 35 45 14 22 50 60 70 80 55 85]]
shape : 	  (1, 12)
size : 	  12


In [38]:
arr1 = np.array([7, 9, 65, 33, 85, 99])
print(arr1)

[ 7  9 65 33 85 99]


In [39]:
arr2 = np.array([[1,2,4] , [2,3,0] , [0,5,1]])
print(arr2)

[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [40]:
arr2.shape

(3, 3)

In [43]:
arr2 = arr2.reshape(1,9)
arr2.shape

(1, 9)

In [45]:
arr3 = np.array([[1,2,4] , [2,3,0] , [0,5,1] , [3,6,9]])
print(arr3)
arr3.shape

[[1 2 4]
 [2 3 0]
 [0 5 1]
 [3 6 9]]


(4, 3)

In [55]:
arr3 = arr3.reshape(2,6)
print(arr3.shape)
print(arr3)

(2, 6)
[[1 2 4 2 3 0]
 [0 5 1 3 6 9]]


In [51]:
table = np.arange(5,10,2)
table

array([5, 7, 9])

In [53]:
space = np.linspace(0,100,15)
space

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [56]:
arr4 = np.repeat(5,5)
print(arr4)

[5 5 5 5 5]


In [57]:
i_array = np.eye(5)
print(i_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [58]:
table

array([5, 7, 9])

In [60]:
arr3 = arr3.reshape(4,3)
arr3

array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1],
       [3, 6, 9]])

In [62]:
print("1. ",2 * arr3)
print("\n")
print("2. ",2 + arr3)
print("\n")
print("3. ", arr3-2)
print("\n")
print("4. ", arr3/2)
print("\n")
print("5. ", arr3**3)
print("\n")
print("6. ", arr3<5)


1.  [[ 2  4  8]
 [ 4  6  0]
 [ 0 10  2]
 [ 6 12 18]]


2.  [[ 3  4  6]
 [ 4  5  2]
 [ 2  7  3]
 [ 5  8 11]]


3.  [[-1  0  2]
 [ 0  1 -2]
 [-2  3 -1]
 [ 1  4  7]]


4.  [[0.5 1.  2. ]
 [1.  1.5 0. ]
 [0.  2.5 0.5]
 [1.5 3.  4.5]]


5.  [[  1   8  64]
 [  8  27   0]
 [  0 125   1]
 [ 27 216 729]]


6.  [[ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True False False]]


In [ ]:
l1 = list(range(0,5001,5))
l1

In [66]:
l2 = np.arange(0,5001,5)
l2

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [67]:
%timeit l2 + 5

1.28 µs ± 10 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [69]:
%timeit [5 in l1]

94 ns ± 0.934 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [73]:
word = np.array(["one" , "two" , "three" , "four"])

print(np.isin(word , "e"))

print("e" in word)
["e" in x for x in word]

[False False False False]
False


[True, False, True, False]

In [77]:
arr3.shape
print(arr3 , "\n")
print(arr3.T)



[[1 2 4]
 [2 3 0]
 [0 5 1]
 [3 6 9]] 

[[1 2 0 3]
 [2 3 5 6]
 [4 0 1 9]]


In [78]:
arr3.dtype

dtype('int64')

In [80]:
int_with_string = np.array([4,5,6,'22','65'])
int_with_string
int_with_string.dtype


dtype('<U21')

In [81]:
int_with_string = np.array([4,5,6,'22','65'], dtype='int32')
int_with_string

array([ 4,  5,  6, 22, 65], dtype=int32)

In [82]:
int_with_string = np.array([4,5,6,'22','65'])
int_with_string

array(['4', '5', '6', '22', '65'], dtype='<U21')

In [124]:

int_with_string.dtype = 'int32'
print(int_with_string)


[52  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 54  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 50 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0]


In [84]:
int_with_string.size

105

In [85]:
int_with_string.size/21

5.0

In [86]:
np.array([4,5,6,'22','65']).size

5

In [87]:
int_with_string = np.array([4,5,6,'22','65'])
print(int_with_string)
print(int_with_string.astype('int32'))



['4' '5' '6' '22' '65']
[ 4  5  6 22 65]


EXCERCISE1

In [90]:
list1 = np.array(['4','5','6','22','65'])
print(list1)
print(int_with_string.astype('float'))


['4' '5' '6' '22' '65']
[ 4.  5.  6. 22. 65.]


In [97]:
print(arr3)
print("\n")
print(arr3.shape)
print("\n")
print(arr3.size)
print("\n")
arr5 = arr3.T
print(arr5)
print("\n")
print(arr5.shape)
print("\n")
print(arr5.size)

[[1 2 4]
 [2 3 0]
 [0 5 1]
 [3 6 9]]


(4, 3)


12


[[1 2 0 3]
 [2 3 5 6]
 [4 0 1 9]]


(3, 4)


12


In [98]:
print(arr5.astype('bool'))


[[ True  True False  True]
 [ True  True  True  True]
 [ True False  True  True]]


In [99]:
table

array([5, 7, 9])

In [100]:
table[0]

5

In [101]:
table[-1]

9

In [102]:
table[:2]

array([5, 7])

In [104]:
arr5
arr5[:2,:2]


array([[1, 2],
       [2, 3]])

EXCERCISE 2

In [105]:
arr6 = np.zeros(50)
arr6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [106]:
arr7 = np.repeat(2,20)
arr7

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [107]:
a1 = np.arange(0,6.28,0.1)
a1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [108]:
a2 = np.array([1,2,3,4,5,6,9,8,7,4,1,5])
a2


array([1, 2, 3, 4, 5, 6, 9, 8, 7, 4, 1, 5])

In [110]:
a2[:5]

array([1, 2, 3, 4, 5])

In [115]:
a3 = a2[::-1]
a3

array([5, 1, 4, 7, 8, 9, 6, 5, 4, 3, 2, 1])

In [122]:
a2[-3:]

array([4, 1, 5])

In [120]:
a2[3:6]


array([4, 5, 6])

In [125]:
a4 = np.flip(a2)
a4

array([5, 1, 4, 7, 8, 9, 6, 5, 4, 3, 2, 1])

In [127]:
print(a4[::-1])


[1 2 3 4 5 6 9 8 7 4 1 5]


In [128]:
print(a4[::2])


[5 4 8 6 4 2]


EXCERCISE 3

In [129]:
a2

array([1, 2, 3, 4, 5, 6, 9, 8, 7, 4, 1, 5])

In [130]:
print(a2[::-1])

[5 1 4 7 8 9 6 5 4 3 2 1]


In [133]:
print(a2[::4])

[1 5 7]


In [134]:
print(a2[::-2])

[5 4 8 6 4 2]


In [137]:
np.array([1.65432, 5.98765]).round(3)

array([1.654, 5.988])

In [141]:
num = np.arange(0,20,0.7555)
num

array([ 0.    ,  0.7555,  1.511 ,  2.2665,  3.022 ,  3.7775,  4.533 ,
        5.2885,  6.044 ,  6.7995,  7.555 ,  8.3105,  9.066 ,  9.8215,
       10.577 , 11.3325, 12.088 , 12.8435, 13.599 , 14.3545, 15.11  ,
       15.8655, 16.621 , 17.3765, 18.132 , 18.8875, 19.643 ])

EXCERCISE 4

In [152]:
print("min = ",    np.min(num).round(2))
print("max = ",    np.max(num).round(2))
print("sum = ",    np.sum(num).round(2))
print("mean = ",   np.mean(num).round(2))
print("median = ", np.median(num).round(2))
print("var = ",    np.var(num).round(2))
print("std = ",    np.std(num).round(2))

min =  0.0
max =  19.64
sum =  265.18
mean =  9.82
median =  9.82
var =  34.63
std =  5.88


In [145]:
new = np.random.choice([0,9,5,7],100)
new

array([0, 9, 0, 5, 0, 5, 9, 5, 9, 0, 9, 5, 9, 9, 9, 5, 9, 0, 7, 0, 7, 7,
       7, 9, 7, 5, 0, 9, 0, 9, 5, 9, 5, 7, 7, 9, 9, 5, 7, 9, 5, 0, 5, 0,
       5, 7, 5, 0, 7, 0, 0, 9, 5, 5, 9, 0, 7, 0, 0, 9, 7, 7, 9, 5, 9, 0,
       7, 7, 5, 0, 9, 9, 9, 7, 7, 9, 7, 7, 0, 9, 7, 9, 5, 9, 7, 7, 9, 0,
       0, 0, 9, 9, 9, 5, 0, 0, 0, 7, 7, 0])

In [159]:
np.random.rand(10,20,9)


array([[[0.17944519, 0.1830022 , 0.12769244, ..., 0.26269295,
         0.30339008, 0.21358491],
        [0.36036795, 0.00408377, 0.84444847, ..., 0.77640219,
         0.6037144 , 0.90600013],
        [0.86354543, 0.68652575, 0.70965766, ..., 0.45068521,
         0.45766443, 0.12326899],
        ...,
        [0.63591124, 0.21598882, 0.31542042, ..., 0.96864852,
         0.08730382, 0.22670452],
        [0.12993877, 0.6037701 , 0.11926718, ..., 0.55370408,
         0.44477975, 0.5956197 ],
        [0.15928322, 0.91769361, 0.52364984, ..., 0.90369537,
         0.97351963, 0.78420275]],

       [[0.2682459 , 0.95602483, 0.86799551, ..., 0.25878511,
         0.13620802, 0.96724368],
        [0.08649158, 0.62462205, 0.91566462, ..., 0.17786827,
         0.09059035, 0.58679487],
        [0.01422938, 0.86804645, 0.34788199, ..., 0.99264636,
         0.85556032, 0.34730237],
        ...,
        [0.11657687, 0.62881935, 0.7932122 , ..., 0.42161693,
         0.52555663, 0.65805118],
        [0.0

In [160]:
mu , sigma = 0 , 0.1
a = np.random.normal(mu , sigma ,1000)

a

array([-9.18692023e-02,  7.63574890e-02, -4.13699117e-02,  5.52555410e-02,
       -5.05995219e-02, -5.10078024e-02, -4.37616878e-02,  6.01270313e-02,
       -7.64368004e-02, -5.34068862e-03,  1.08382737e-01, -3.24093321e-02,
        1.55655966e-01,  1.50192845e-01, -1.07569884e-01, -6.25155074e-02,
       -1.47401721e-01, -1.15533212e-02, -1.33656431e-01, -1.13557374e-01,
       -6.41707298e-02,  4.30002895e-02, -3.70017960e-02, -3.89631015e-03,
       -3.66251095e-02,  2.85287054e-02, -3.84808240e-02,  2.76510272e-02,
       -9.80953721e-02,  8.62650794e-02, -1.44871451e-02,  1.15209305e-01,
       -6.21308437e-02, -3.02933998e-02, -1.15457895e-01,  4.39518786e-02,
       -7.36963916e-02,  7.70106487e-02, -1.31024312e-01, -5.07161423e-02,
        7.24780562e-03,  1.26790163e-01, -5.60664394e-02,  1.52995824e-01,
       -1.56789721e-01, -3.54102364e-02, -1.74042604e-01,  1.39881312e-01,
        8.67036239e-02,  4.81569222e-02,  1.07511886e-01,  4.61465685e-02,
       -3.70620645e-02, -

EXCERCISE 5

In [158]:
dice_res = np.random.choice([1,2,3,4,5,6],10)
dice_res

array([4, 6, 3, 1, 3, 2, 5, 6, 4, 3])

In [168]:
coin_res = np.random.choice(['h','h','t'],3)
coin_res 

array(['h', 't', 'h'], dtype='<U1')